# Generated by Django 3.2 on 2025-05-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default='Описание произведения'),
            preserve_default=False,
        ),
    ]
