# Generated by Django 3.2 on 2025-05-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_title_description'),
        ('reviews', '0003_auto_20250528_2313'),
    ]

    operations = [
    ]
